Development
slydevruby/third pull request #2
Opened 2024-02-16 10:20 UTC by slydevruby

Заполнил сущности, изменил стиль, переформатировал шаблоны, добавил местоположение

2024-02-16 14:43 UTC, VidgarVii requested changes

2024-02-16 14:43 UTC, VidgarVii commented on README.md
> +* Таблица Ролей
ТЗ:
> Добавьте в README.md список сущностей ... А не таблиц.
список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется
Как и на 1 блоке создавали такие сущности как Поезд, вагон, вокзал и т. д.

2024-02-16 14:43 UTC, VidgarVii commented on app/assets/stylesheets/simple.css
> +#page { margin: auto; width: 70% }
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-02-16 14:43 UTC, VidgarVii commented on app/views/about/author.html.erb
>  <!-- app/views/pages/about.html.erb -->
в мастер ветке этого фалйа не должно быть. Получается уже мастер не корректен, что очень плохо.

2024-02-16 14:43 UTC, VidgarVii commented on app/views/about/author.html.erb
`html` файлы целиком статические
их будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2024-02-16 14:43 UTC, VidgarVii commented on app/views/about/show.html.erb
> +      <a href="https://thinknetica.com">Онлайн-школа Thinknetica </a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2024-02-16 14:43 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
стоит разобраться что делает этот конфиг.
В ТЗ про него ни чего сказано не было

2024-02-16 14:43 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2024-02-17 06:59 UTC, slydevruby commented on README.md
> +* Таблица Ролей
Не понял. Описать в виде : Объект (свойства, методы) ?
класс Тест
  атрибуты: вопросы, ответы

Так?

2024-02-18 09:02 UTC, closed without merging